steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/chronopin', '-f', 'Docker/Dockerfile', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/${PROJECT_ID}/chronopin"]

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/chronopin-dep'
  - 'chronopin=gcr.io/$PROJECT_ID/chronopin:latest'