kind: Service
apiVersion: v1
metadata:
  name: chronopin-web
spec:
  type: NodePort
  #type: LoadBalancer
  selector:
    app: website
    role: frontend
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000