-- Baseline PostgreSQL schema, ported from the SQL Server tables in
-- scripts/db/createTable (see git history) plus every column their
-- migrations added.
--
-- Identifiers are camelCase and double-quoted throughout, so query rows come
-- back with the same property names the models have always used. An unquoted
-- identifier is folded to lower case by PostgreSQL.
--
-- Ids are GENERATED BY DEFAULT rather than ALWAYS so seeding and the SQL
-- Server transfer can keep existing ids; both reset the sequences afterwards.

CREATE EXTENSION IF NOT EXISTS postgis;
-- SQL Server compared strings case-insensitively. citext keeps that for the
-- columns people type into: logging in by email, and user:/company:/category:
-- search terms.
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE "User" (
  "id"                          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userName"                    citext NOT NULL,
  "firstName"                   varchar(255) NOT NULL,
  "lastName"                    varchar(255) NOT NULL,
  "gender"                      varchar(255),
  "locale"                      char(5),
  "facebookId"                  varchar(25),
  "googleId"                    varchar(25),
  "pictureUrl"                  varchar(1000),
  "fbUpdatedTime"               timestamptz,
  "fbVerified"                  boolean,
  "googleVerified"              boolean,
  "about"                       varchar(1000),
  "email"                       citext,
  "password"                    varchar(255),
  "role"                        varchar(255) DEFAULT 'user',
  "provider"                    varchar(255),
  "salt"                        varchar(255),
  "websiteUrl"                  varchar(500),
  "defaultFilterSpanPreference" varchar(20),
  "utcCreatedDateTime"          timestamptz NOT NULL DEFAULT now(),
  "utcUpdatedDateTime"          timestamptz,
  "utcDeletedDateTime"          timestamptz
);

CREATE TABLE "Pin" (
  "id"                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parentId"                integer,
  "title"                   varchar(1024) NOT NULL,
  "description"             varchar(4000),
  "sourceUrl"               varchar(4000),
  "longFormSummary"         text,
  -- The place label only. Coordinates live in "location".
  "address"                 varchar(4000),
  "location"                geography(Point, 4326),
  "priceLowerBound"         numeric(18, 2),
  "priceUpperBound"         numeric(18, 2),
  "price"                   numeric(18, 2),
  "priceCurrency"           varchar(3),
  "tip"                     varchar(4000),
  "dateConfidence"          varchar(32),
  "dateConfidenceReasoning" varchar(4000),
  "company"                 citext,
  "companyWikiUrl"          varchar(2048),
  "category"                citext,
  "utcStartDateTime"        timestamptz NOT NULL,
  "utcEndDateTime"          timestamptz,
  "allDay"                  boolean NOT NULL DEFAULT false,
  "userId"                  integer NOT NULL,
  "utcCreatedDateTime"      timestamptz NOT NULL DEFAULT now(),
  "utcUpdatedDateTime"      timestamptz,
  "utcDeletedDateTime"      timestamptz
);
CREATE INDEX "IX_Pin_utcStartDateTime" ON "Pin" ("utcStartDateTime", "id");
CREATE INDEX "IX_Pin_parentId" ON "Pin" ("parentId");
CREATE INDEX "IX_Pin_location" ON "Pin" USING GIST ("location");

CREATE TABLE "Medium" (
  "id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "thumbName"      varchar(4000),
  "thumbWidth"     integer,
  "thumbHeight"    integer,
  "originalUrl"    varchar(4000),
  "originalWidth"  integer,
  "originalHeight" integer,
  "type"           varchar(255) NOT NULL,
  "authorName"     varchar(1028),
  "authorUrl"      varchar(4000),
  "html"           varchar(4000)
);

CREATE TABLE "MediumType" (
  "id"   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(255) NOT NULL
);

CREATE TABLE "PinMedium" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pinId"              integer NOT NULL,
  "mediumId"           integer NOT NULL,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  "utcDeletedDateTime" timestamptz,
  CONSTRAINT "PinMedium_mediumId_pinId_unique" UNIQUE ("pinId", "mediumId")
);

CREATE TABLE "Favorite" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"             integer NOT NULL,
  "pinId"              integer NOT NULL,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  "utcUpdatedDateTime" timestamptz,
  "utcDeletedDateTime" timestamptz,
  CONSTRAINT "UC_favorite_userId_pinId" UNIQUE ("userId", "pinId")
);

CREATE TABLE "Like" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "like"               boolean NOT NULL,
  "userId"             integer NOT NULL,
  "pinId"              integer NOT NULL,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  "utcUpdatedDateTime" timestamptz,
  "utcDeletedDateTime" timestamptz,
  CONSTRAINT "UC_like_userId_pinId" UNIQUE ("userId", "pinId")
);

CREATE TABLE "Comment" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "text"               varchar(4000) NOT NULL,
  "userId"             integer NOT NULL,
  "pinId"              integer NOT NULL,
  "parentCommentId"    integer,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  "utcUpdatedDateTime" timestamptz,
  "utcDeletedDateTime" timestamptz
);
CREATE INDEX "IX_Comment_pinId" ON "Comment" ("pinId");

CREATE TABLE "Merchant" (
  "id"    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pinId" integer NOT NULL,
  "label" varchar(1024),
  "url"   varchar(1024),
  "price" numeric(18, 2)
);
CREATE INDEX "IX_Merchant_pinId" ON "Merchant" ("pinId");

CREATE TABLE "DateTime" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title"              varchar(1024) NOT NULL,
  "description"        varchar(4000),
  "sourceUrl"          varchar(4000),
  "address"            varchar(4000),
  "tip"                varchar(4000),
  "utcStartDateTime"   timestamptz NOT NULL,
  "utcEndDateTime"     timestamptz,
  "allDay"             boolean NOT NULL DEFAULT false,
  "alwaysShow"         boolean NOT NULL DEFAULT false,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  "utcUpdatedDateTime" timestamptz
);
CREATE INDEX "IX_DateTime_utcStartDateTime" ON "DateTime" ("utcStartDateTime");

CREATE TABLE "Click" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"             integer NOT NULL,
  "mediumId"           integer NOT NULL,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now()
);

-- One row per pin per joined medium/merchant, the shape Pins.mapPinJoins
-- folds back into nested objects. Grouping by the primary key makes every
-- other Pin column functionally dependent, so they need no GROUP BY entry;
-- only the joined columns do.
CREATE VIEW "PinBaseView" AS
SELECT
  "Pin"."id",
  "Pin"."parentId",
  "Pin"."title",
  "Pin"."description",
  "Pin"."sourceUrl",
  "Pin"."longFormSummary",
  "Pin"."address",
  -- Plain numbers, so nothing above this view handles the spatial type.
  ST_Y("Pin"."location"::geometry)             AS "latitude",
  ST_X("Pin"."location"::geometry)             AS "longitude",
  "Pin"."priceLowerBound",
  "Pin"."priceUpperBound",
  "Pin"."price",
  "Pin"."priceCurrency",
  "Pin"."tip",
  "Pin"."dateConfidence",
  "Pin"."dateConfidenceReasoning",
  "Pin"."company",
  "Pin"."companyWikiUrl",
  "Pin"."category",
  "Pin"."utcStartDateTime",
  "Pin"."utcEndDateTime",
  "Pin"."allDay",
  "Pin"."userId",
  "Pin"."utcCreatedDateTime",
  "Pin"."utcUpdatedDateTime",
  "Pin"."utcDeletedDateTime",

  COUNT("Favorites"."id")::integer             AS "favoriteCount",
  COUNT("Likes"."id")::integer                 AS "likeCount",
  ("Pin"."parentId" IS NULL AND EXISTS (
    SELECT 1 FROM "Pin" AS "child" WHERE "child"."parentId" = "Pin"."id"
  ))                                           AS "rootThread",

  "Media"."id"                                 AS "Media.id",
  "Media"."thumbName"                          AS "Media.thumbName",
  "Media"."thumbWidth"                         AS "Media.thumbWidth",
  "Media"."thumbHeight"                        AS "Media.thumbHeight",
  "Media"."originalUrl"                        AS "Media.originalUrl",
  "Media"."originalWidth"                      AS "Media.originalWidth",
  "Media"."originalHeight"                     AS "Media.originalHeight",
  "Media"."type"                               AS "Media.type",
  "Media"."authorName"                         AS "Media.authorName",
  "Media"."authorUrl"                          AS "Media.authorUrl",
  "Media"."html"                               AS "Media.html",

  "User"."userName"                            AS "User.userName",

  "Merchant"."id"                              AS "Merchant.id",
  "Merchant"."label"                           AS "Merchant.label",
  "Merchant"."url"                             AS "Merchant.url",
  "Merchant"."price"                           AS "Merchant.price"

FROM "Pin"
  LEFT JOIN "PinMedium" AS "Media.PinMedium"
    ON "Pin"."id" = "Media.PinMedium"."pinId"
  LEFT JOIN "Medium" AS "Media"
    ON "Media"."id" = "Media.PinMedium"."mediumId" AND "Media.PinMedium"."utcDeletedDateTime" IS NULL
  LEFT JOIN "Favorite" AS "Favorites"
    ON "Pin"."id" = "Favorites"."pinId" AND "Favorites"."utcDeletedDateTime" IS NULL
  LEFT JOIN "Like" AS "Likes"
    ON "Pin"."id" = "Likes"."pinId" AND "Likes"."utcDeletedDateTime" IS NULL
  LEFT JOIN "User"
    ON "Pin"."userId" = "User"."id"
  LEFT JOIN "Merchant"
    ON "Pin"."id" = "Merchant"."pinId"

GROUP BY
  "Pin"."id",
  "Media"."id",
  "User"."userName",
  "Merchant"."id";
