-- Following another user, and the notifications that tell someone about it.

-- One row per follower/followee pair. Unfollowing soft-deletes the row and
-- following again revives it, the way Favorite works.
CREATE TABLE "Follow" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "followerId"         integer NOT NULL REFERENCES "User" ("id") ON DELETE CASCADE,
  "followeeId"         integer NOT NULL REFERENCES "User" ("id") ON DELETE CASCADE,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  "utcUpdatedDateTime" timestamptz,
  "utcDeletedDateTime" timestamptz,
  CONSTRAINT "UC_Follow_followerId_followeeId" UNIQUE ("followerId", "followeeId"),
  CONSTRAINT "CK_Follow_not_self" CHECK ("followerId" <> "followeeId")
);

CREATE INDEX "IX_Follow_followeeId" ON "Follow" ("followeeId");

-- What the navbar bell lists. "userId" is who sees it, "actorId" who caused
-- it. "type" is 'follow' for now; "pinId" is there for pin-shaped kinds
-- (comments, favorites) later and is null for a follow.
CREATE TABLE "Notification" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"             integer NOT NULL REFERENCES "User" ("id") ON DELETE CASCADE,
  "actorId"            integer NOT NULL REFERENCES "User" ("id") ON DELETE CASCADE,
  "type"               varchar(50) NOT NULL,
  "pinId"              integer,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  "utcReadDateTime"    timestamptz,
  "utcDeletedDateTime" timestamptz
);

CREATE INDEX "IX_Notification_userId_utcCreatedDateTime" ON "Notification" ("userId", "utcCreatedDateTime" DESC);
