-- Companies become rows of their own instead of free text repeated on every
-- pin, so a company's Wikipedia link and logo are stored once and every pin
-- about it shares them. The API still takes a company name; Company.resolve
-- turns it into "Pin"."companyId".
--
-- logoUrl is a best attempt (scripts/company/logos.js): the company website's
-- icon, else a squarish Wikidata logo, else NULL. utcLogoCheckedDateTime marks
-- that the attempt was made, so a company with no findable logo is not retried
-- on every pin save.

CREATE TABLE "Company" (
  "id"                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"                   citext NOT NULL,
  "wikiUrl"                varchar(2048),
  "websiteUrl"             varchar(2048),
  "logoUrl"                varchar(2048),
  "utcLogoCheckedDateTime" timestamptz,
  "utcCreatedDateTime"     timestamptz NOT NULL DEFAULT now(),
  "utcUpdatedDateTime"     timestamptz,
  CONSTRAINT "UC_Company_name" UNIQUE ("name")
);

-- Every name already on a pin. Existing data has one wiki URL per name, but
-- max() picks deterministically if that ever stops being true.
INSERT INTO "Company" ("name", "wikiUrl")
SELECT btrim("company"), max("companyWikiUrl")
FROM "Pin"
WHERE btrim("company") <> ''
GROUP BY btrim("company");

ALTER TABLE "Pin" ADD COLUMN "companyId" integer REFERENCES "Company" ("id") ON DELETE SET NULL;
CREATE INDEX "IX_Pin_companyId" ON "Pin" ("companyId");

UPDATE "Pin"
SET "companyId" = "Company"."id"
FROM "Company"
WHERE "Company"."name" = btrim("Pin"."company");

DROP VIEW "PinBaseView";

ALTER TABLE "Pin" DROP COLUMN "company";
ALTER TABLE "Pin" DROP COLUMN "companyWikiUrl";

-- As in 0001, with the company columns now coming from "Company". They keep
-- their old names so readers of the view ("company:" search, pin JSON) do not
-- change.
CREATE VIEW "PinBaseView" AS
SELECT
  "Pin"."id",
  "Pin"."parentId",
  "Pin"."title",
  "Pin"."description",
  "Pin"."sourceUrl",
  "Pin"."longFormSummary",
  "Pin"."address",
  ST_Y("Pin"."location"::geometry)             AS "latitude",
  ST_X("Pin"."location"::geometry)             AS "longitude",
  "Pin"."priceLowerBound",
  "Pin"."priceUpperBound",
  "Pin"."price",
  "Pin"."priceCurrency",
  "Pin"."tip",
  "Pin"."dateConfidence",
  "Pin"."dateConfidenceReasoning",
  "Pin"."companyId",
  "Company"."name"                             AS "company",
  "Company"."wikiUrl"                          AS "companyWikiUrl",
  "Company"."logoUrl"                          AS "companyLogoUrl",
  "Pin"."category",
  "Pin"."utcStartDateTime",
  "Pin"."utcEndDateTime",
  "Pin"."allDay",
  "Pin"."userId",
  "Pin"."utcCreatedDateTime",
  "Pin"."utcUpdatedDateTime",
  "Pin"."utcDeletedDateTime",

  COUNT("Favorites"."id")::integer             AS "favoriteCount",
  COUNT("Likes"."id")::integer                 AS "likeCount",
  ("Pin"."parentId" IS NULL AND EXISTS (
    SELECT 1 FROM "Pin" AS "child" WHERE "child"."parentId" = "Pin"."id"
  ))                                           AS "rootThread",

  "Media"."id"                                 AS "Media.id",
  "Media"."thumbName"                          AS "Media.thumbName",
  "Media"."thumbWidth"                         AS "Media.thumbWidth",
  "Media"."thumbHeight"                        AS "Media.thumbHeight",
  "Media"."originalUrl"                        AS "Media.originalUrl",
  "Media"."originalWidth"                      AS "Media.originalWidth",
  "Media"."originalHeight"                     AS "Media.originalHeight",
  "Media"."type"                               AS "Media.type",
  "Media"."authorName"                         AS "Media.authorName",
  "Media"."authorUrl"                          AS "Media.authorUrl",
  "Media"."html"                               AS "Media.html",

  "User"."userName"                            AS "User.userName",

  "Merchant"."id"                              AS "Merchant.id",
  "Merchant"."label"                           AS "Merchant.label",
  "Merchant"."url"                             AS "Merchant.url",
  "Merchant"."price"                           AS "Merchant.price"

FROM "Pin"
  LEFT JOIN "Company"
    ON "Pin"."companyId" = "Company"."id"
  LEFT JOIN "PinMedium" AS "Media.PinMedium"
    ON "Pin"."id" = "Media.PinMedium"."pinId"
  LEFT JOIN "Medium" AS "Media"
    ON "Media"."id" = "Media.PinMedium"."mediumId" AND "Media.PinMedium"."utcDeletedDateTime" IS NULL
  LEFT JOIN "Favorite" AS "Favorites"
    ON "Pin"."id" = "Favorites"."pinId" AND "Favorites"."utcDeletedDateTime" IS NULL
  LEFT JOIN "Like" AS "Likes"
    ON "Pin"."id" = "Likes"."pinId" AND "Likes"."utcDeletedDateTime" IS NULL
  LEFT JOIN "User"
    ON "Pin"."userId" = "User"."id"
  LEFT JOIN "Merchant"
    ON "Pin"."id" = "Merchant"."pinId"

GROUP BY
  "Pin"."id",
  "Company"."id",
  "Media"."id",
  "User"."userName",
  "Merchant"."id";
