-- Notes for the AI on what an existing pin is missing. When someone creating a
-- pin finds the event is already pinned, they can describe what the existing
-- pin lacks instead of posting a duplicate. Rows wait here for the AI (or an
-- admin) to act on; nothing applies them automatically yet.

CREATE TABLE "AiFeedback" (
  "id"                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pinId"               integer NOT NULL REFERENCES "Pin" ("id") ON DELETE CASCADE,
  "userId"              integer REFERENCES "User" ("id") ON DELETE SET NULL,
  "feedback"            varchar(2000) NOT NULL,
  -- The link the person was about to pin, as context for the feedback.
  "sourceUrl"           varchar(4000),
  "status"              varchar(20) NOT NULL DEFAULT 'open' CHECK ("status" IN ('open', 'applied', 'dismissed')),
  "utcCreatedDateTime"  timestamptz NOT NULL DEFAULT now(),
  "utcResolvedDateTime" timestamptz
);
CREATE INDEX "IX_AiFeedback_pinId" ON "AiFeedback" ("pinId");
CREATE INDEX "IX_AiFeedback_open" ON "AiFeedback" ("utcCreatedDateTime") WHERE "status" = 'open';
