-- An Open Knowledge Format (OKF, v0.2) wiki per link. Every link a pin
-- cites - its sourceUrl and each reference, whether a web page, YouTube
-- video, tweet or podcast episode - gets one
-- Source row, and Claude writes that link's content up once as a small tree
-- of SourceWiki pages: a root page for the whole link, fanning out to more
-- granular pages (a roundup's items, a long video's parts, a podcast's
-- segments), which can fan out again.
--
-- A pin's long-form summary is then rebuilt from its links' wikis rather than
-- from the pages themselves, so a new link costs one fetch and one wiki, and
-- the links the pin already had are never fetched again
-- (src/server/services/sourceWiki.ts).
--
-- Sources are keyed by the link (src/lib/citations.ts urlKey), not by pin:
-- two pins citing the same article share its wiki, which is written about the
-- page itself rather than about either pin.
--
-- The rows hold what an OKF concept needs, and src/server/okf renders them as
-- a bundle: each wiki page a concept (type, title, description = summary,
-- tags, body), the link its resource and its one source, generatedBy and
-- utcBuiltDateTime its generated: {by, at}; each pin a concept whose sources
-- are its links' concepts. https://github.com/GoogleCloudPlatform/open-knowledge-format

CREATE TABLE "Source" (
  "id"                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- urlKey is capped well below the btree row limit; longer links are skipped.
  "urlKey"               varchar(2000) NOT NULL CONSTRAINT "UQ_Source_urlKey" UNIQUE,
  "url"                  varchar(4000) NOT NULL,
  "kind"                 varchar(16) NOT NULL CONSTRAINT "CK_Source_kind" CHECK ("kind" IN ('web', 'youtube', 'tweet', 'podcast')),
  "title"                varchar(1024),
  -- pending: no wiki yet. ready: wikiVersion is current. failed: the last
  -- fetch or write-up failed (lastError), to be retried while attempts last.
  "status"               varchar(16) NOT NULL DEFAULT 'pending' CONSTRAINT "CK_Source_status" CHECK ("status" IN ('pending', 'ready', 'failed')),
  -- The text the wiki was written from (page text, video description and
  -- transcript, tweet), kept so a wiki can be rewritten without a refetch.
  "text"                 text,
  "textHash"             varchar(64),
  -- The source's own publication or last-update day, as the wiki's writer
  -- read it off the text: OKF sources[].last_modified.
  "sourceModifiedDate"   date,
  -- The OKF actor that wrote the current wiki, "<producer>/<model>".
  "generatedBy"          varchar(128),
  -- Bumped each time the wiki is (re)written; 0 until the first one.
  "wikiVersion"          integer NOT NULL DEFAULT 0,
  "attempts"             smallint NOT NULL DEFAULT 0,
  "lastError"            varchar(2000),
  "utcFetchedDateTime"   timestamptz,
  "utcAttemptedDateTime" timestamptz,
  "utcBuiltDateTime"     timestamptz,
  "utcCreatedDateTime"   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "IX_Source_status" ON "Source" ("status");

-- One source's wiki pages: exactly one root (parentId NULL) and any number of
-- sub-pages below it. Replaced wholesale when the wiki is rewritten.
CREATE TABLE "SourceWiki" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sourceId"           integer NOT NULL REFERENCES "Source" ("id") ON DELETE CASCADE,
  "parentId"           integer REFERENCES "SourceWiki" ("id") ON DELETE CASCADE,
  -- Order among its siblings, as the source has them.
  "position"           smallint NOT NULL DEFAULT 0,
  -- OKF concept type: the link's kind for a root ("Web Page", "YouTube
  -- Video", ...), "Source Part" or "Topic" below it.
  "type"               varchar(64) NOT NULL,
  "title"              varchar(1024) NOT NULL,
  -- A line on what the page covers, for choosing which pages to read.
  "summary"            varchar(2000) NOT NULL,
  -- Markdown: what the source says - events, dates in its own words, places,
  -- people, organizations, figures, quotes.
  "body"               text NOT NULL,
  -- OKF tags: short lowercase subjects (organizations, places, products).
  "tags"               varchar(64)[] NOT NULL DEFAULT '{}',
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "IX_SourceWiki_sourceId" ON "SourceWiki" ("sourceId");
CREATE INDEX "IX_SourceWiki_parentId" ON "SourceWiki" ("parentId");
CREATE UNIQUE INDEX "UQ_SourceWiki_root" ON "SourceWiki" ("sourceId") WHERE "parentId" IS NULL;

-- Which sources a pin cites, and whether its summary has taken each one in.
-- Kept in step with Pin.sourceUrl and PinReference by the app, matched by
-- urlKey: PinReference rows are deleted and re-inserted on every edit, so
-- their ids cannot be held on to.
CREATE TABLE "PinSource" (
  "pinId"                 integer NOT NULL REFERENCES "Pin" ("id") ON DELETE CASCADE,
  "sourceId"              integer NOT NULL REFERENCES "Source" ("id") ON DELETE CASCADE,
  -- 'source' for Pin.sourceUrl, 'reference' for a PinReference.
  "role"                  varchar(16) NOT NULL CONSTRAINT "CK_PinSource_role" CHECK ("role" IN ('source', 'reference')),
  -- The source's wikiVersion the pin's summary was last built from; NULL
  -- until the summary has taken this source in.
  "summarizedWikiVersion" integer,
  -- Set when the pin stops citing the source. The row stays until the next
  -- summary rebuild, so that rebuild knows to happen and leaves it out.
  "utcRemovedDateTime"    timestamptz,
  "utcCreatedDateTime"    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("pinId", "sourceId")
);
CREATE INDEX "IX_PinSource_sourceId" ON "PinSource" ("sourceId");
