-- What `npm run okf:lint` found (scripts/okf/lint.ts, docs/okf/playbooks/
-- lint-the-wikis.md). Each run replaces the open findings of the checks it
-- ran, for the pins it ran on, so the table is always the latest word.
--
--   conformance     a generated OKF page breaks the spec (path says which)
--   stale           a link's text has changed since its wiki was written
--   orphan          a link no live pin cites any more
--   quality         a thin, untagged or repetitive wiki; a pin with wikis but no summary
--   contradiction   two of a pin's links disagree about its event (for an admin to review)

CREATE TABLE "OkfLintFinding" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "check"              varchar(32) NOT NULL CONSTRAINT "CK_OkfLintFinding_check"
                         CHECK ("check" IN ('conformance', 'stale', 'orphan', 'quality', 'contradiction')),
  "severity"           varchar(16) NOT NULL CONSTRAINT "CK_OkfLintFinding_severity" CHECK ("severity" IN ('error', 'warning', 'info')),
  "pinId"              integer REFERENCES "Pin" ("id") ON DELETE CASCADE,
  "sourceId"           integer REFERENCES "Source" ("id") ON DELETE CASCADE,
  -- The bundle path, for a conformance finding.
  "path"               varchar(1024),
  "message"            varchar(2000) NOT NULL,
  "detail"             jsonb,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "IX_OkfLintFinding_pinId" ON "OkfLintFinding" ("pinId");
CREATE INDEX "IX_OkfLintFinding_sourceId" ON "OkfLintFinding" ("sourceId");

-- What a check that costs something (a fetch, a Claude call, a rewrite) last
-- looked at, so the next run skips what has not changed since: for
-- contradiction, the pin's links and their wiki versions; for quality, the
-- wiki version it queued for a rewrite (queued once per version, not forever).
CREATE TABLE "OkfLintScan" (
  "check"              varchar(32) NOT NULL,
  "subjectId"          integer NOT NULL,
  "signature"          varchar(128) NOT NULL,
  "utcScannedDateTime" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("check", "subjectId")
);
