-- Stock tickers on pins (src/lib/stocks.ts, src/server/services/pinStocks.ts):
-- a pin about a listed company carries its ticker, with the price when the pin
-- was posted and the close on its start date (again each time the start date
-- moves). The live price is pushed over the live feed, not stored.

-- A company's US listing, looked up once by name (Nasdaq symbol search, only
-- a stock whose name starts with the company's). Null with a check date means
-- none was found: a private company, or one listed elsewhere.
ALTER TABLE "Company"
  ADD COLUMN "tickerSymbol"             varchar(16),
  ADD COLUMN "utcTickerCheckedDateTime" timestamptz;

CREATE TABLE "PinTicker" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pinId"              integer NOT NULL REFERENCES "Pin" ("id") ON DELETE CASCADE,
  "symbol"             varchar(16) NOT NULL,
  "name"               varchar(255),
  "assetClass"         varchar(16) NOT NULL DEFAULT 'stocks' CONSTRAINT "CK_PinTicker_assetClass" CHECK ("assetClass" IN ('stocks', 'etf')),
  -- company: from the pin's company; manual: added by its author or an admin.
  "origin"             varchar(16) NOT NULL CONSTRAINT "CK_PinTicker_origin" CHECK ("origin" IN ('company', 'manual')),
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  -- Taken off by hand. Kept, so the company's ticker is not added back.
  "utcRemovedDateTime" timestamptz,
  CONSTRAINT "UC_PinTicker_pinId_symbol" UNIQUE ("pinId", "symbol")
);

-- posted: the last price known when the pin was posted (a delayed quote, or
--         the close before it when the ticker came later).
-- start:  the close on the pin's start date, one row per start date the pin
--         has had; "price" is null until that day's market has closed.
CREATE TABLE "PinTickerPrice" (
  "id"               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pinTickerId"      integer NOT NULL REFERENCES "PinTicker" ("id") ON DELETE CASCADE,
  "kind"             varchar(8) NOT NULL CONSTRAINT "CK_PinTickerPrice_kind" CHECK ("kind" IN ('posted', 'start')),
  -- start: the pin's start it is for, and that start's market day.
  "utcStartDateTime" timestamptz,
  "day"              date,
  "price"            numeric(16, 4),
  -- When the price was the market's: the trade or the day's close.
  "utcPriceDateTime" timestamptz,
  -- Last looked for while "price" is null, so a day Nasdaq has no close for
  -- (before the listing, too long ago) is not asked about on every view.
  "utcCheckedDateTime" timestamptz,
  -- When the pin was given this start (or posted), for the history's order.
  "utcSetDateTime"   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "CK_PinTickerPrice_start" CHECK ("kind" = 'posted' OR ("utcStartDateTime" IS NOT NULL AND "day" IS NOT NULL))
);
CREATE UNIQUE INDEX "UX_PinTickerPrice_posted" ON "PinTickerPrice" ("pinTickerId") WHERE "kind" = 'posted';
CREATE UNIQUE INDEX "UX_PinTickerPrice_start" ON "PinTickerPrice" ("pinTickerId", "utcStartDateTime") WHERE "kind" = 'start';
