-- Related and supplier companies' tickers beside a pin's own (0029): a story
-- about OpenAI moves Microsoft (investor, cloud partner) and Nvidia (chips).
--
-- A company's relations are found once (Claude, src/server/extract/
-- companyRelations.ts, or set by hand with `npm run stocks:sync -- --relate`)
-- and every pin of the company carries them, like its own ticker.

ALTER TABLE "Company" ADD COLUMN "utcRelationsCheckedDateTime" timestamptz;

CREATE TABLE "CompanyRelation" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "companyId"          integer NOT NULL REFERENCES "Company" ("id") ON DELETE CASCADE,
  "symbol"             varchar(16) NOT NULL,
  "name"               varchar(255),
  "assetClass"         varchar(16) NOT NULL DEFAULT 'stocks' CONSTRAINT "CK_CompanyRelation_assetClass" CHECK ("assetClass" IN ('stocks', 'etf')),
  "relation"           varchar(16) NOT NULL CONSTRAINT "CK_CompanyRelation_relation" CHECK ("relation" IN ('related', 'supplier')),
  -- Why, in a few words ("Largest investor and cloud partner").
  "note"               varchar(300),
  "origin"             varchar(16) NOT NULL CONSTRAINT "CK_CompanyRelation_origin" CHECK ("origin" IN ('claude', 'manual')),
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "UC_CompanyRelation_companyId_symbol" UNIQUE ("companyId", "symbol")
);

-- What a pin's ticker is to it: the company itself, a related company, or a
-- supplier. Tickers added by hand so far were extras, so related.
ALTER TABLE "PinTicker"
  ADD COLUMN "relation" varchar(16) NOT NULL DEFAULT 'company' CONSTRAINT "CK_PinTicker_relation" CHECK ("relation" IN ('company', 'related', 'supplier')),
  ADD COLUMN "note"     varchar(300);
UPDATE "PinTicker" SET "relation" = 'related' WHERE "origin" = 'manual';
