-- Awards a film, series or anime pin's work won or was nominated for, from
-- the award bodies' Wikipedia pages (src/server/awards.ts), matched by the
-- work's name (src/lib/awards.ts). Derived: each sync replaces a pin's rows.
CREATE TABLE "PinAward" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pinId"              integer NOT NULL REFERENCES "Pin" ("id") ON DELETE CASCADE,
  "body"               varchar(120) NOT NULL,
  "award"              varchar(200) NOT NULL,
  "year"               smallint NOT NULL,
  "work"               varchar(300) NOT NULL,
  "result"             varchar(10) NOT NULL CONSTRAINT "CK_PinAward_result" CHECK ("result" IN ('won', 'nominated')),
  "sourceUrl"          varchar(500) NOT NULL,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "UC_PinAward" UNIQUE ("pinId", "body", "award", "year", "work")
);
CREATE INDEX "IX_PinAward_pinId" ON "PinAward" ("pinId");
