-- Following a company, and the company blurb a search for one shows.
--
-- A search that names one company (company:Apple) opens with a panel about
-- it: what the company is in a line, how its pins' comments read lately, and
-- a Follow button. Following a company is like following a person - every new
-- pin for it writes a 'company' notification to the bell.

-- A line about the company, from the first sentences of its Wikipedia article
-- (src/server/companyDescription.ts). A check date with no description means
-- none was found, so a company with no article is not looked up again on
-- every pin save - utcLogoCheckedDateTime works the same way.
ALTER TABLE "Company"
  ADD COLUMN "description"                    varchar(1000),
  ADD COLUMN "utcDescriptionCheckedDateTime"  timestamptz;

-- One row per follower/company pair. Unfollowing soft-deletes the row and
-- following again revives it, as "Follow" does.
CREATE TABLE "CompanyFollow" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"             integer NOT NULL REFERENCES "User" ("id") ON DELETE CASCADE,
  "companyId"          integer NOT NULL REFERENCES "Company" ("id") ON DELETE CASCADE,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  "utcUpdatedDateTime" timestamptz,
  "utcDeletedDateTime" timestamptz,
  CONSTRAINT "UC_CompanyFollow_userId_companyId" UNIQUE ("userId", "companyId")
);

CREATE INDEX "IX_CompanyFollow_companyId" ON "CompanyFollow" ("companyId");

-- Which company a 'company' notification is about; null for every other kind.
-- Plain integer, as "pinId" and "commentId" are: a company that went away
-- leaves the row to be dropped by the join in Notification's VISIBLE_FROM.
-- The unique index keeps a follower to one notification per pin and company,
-- so a pin saved again does not stack up bell entries, as 'today' does.
ALTER TABLE "Notification" ADD COLUMN "companyId" integer;

CREATE UNIQUE INDEX "UX_Notification_company" ON "Notification" ("userId", "pinId", "companyId") WHERE "type" = 'company';
