-- The daily pin jobs (src/server/jobs, docs/okf/scraping/daily-jobs.md): an
-- LLM-orchestrated run at the times an admin sets, that scrapes new pins and
-- maintains existing ones.
--
-- "JobRun" is one run of one job. A scheduled run claims its slot - the job
-- and the local time it was due, e.g. 'news@2026-09-22T06:00 America/Los_Angeles'
-- - through the unique key, so it happens once however many servers tick; a
-- run started by hand gets a slot of its own ('manual:<iso>').
--
--   status    running -> ok | failed | skipped (no LLM was available)
--   driver    who did the reasoning: 'api' (the app's Anthropic key) or
--             'session' (a headless Claude Code on the host, on its login)
--   actions   [{ at, tool, pinId?, title?, detail }] - every write, in order
--   learnings [{ at, topic, text }] - what the run says the strategy should
--             learn; the next runs read the newest back into their prompt
--   report    the model's closing summary
--   usage     tokens and cost as the driver reported them
CREATE TABLE "JobRun" (
  "id"                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "jobId"               varchar(40) NOT NULL,
  "slot"                varchar(120) NOT NULL,
  "trigger"             varchar(10) NOT NULL CONSTRAINT "CK_JobRun_trigger" CHECK ("trigger" IN ('schedule', 'manual')),
  "status"              varchar(10) NOT NULL DEFAULT 'running' CONSTRAINT "CK_JobRun_status" CHECK ("status" IN ('running', 'ok', 'failed', 'skipped')),
  "driver"              varchar(10) CONSTRAINT "CK_JobRun_driver" CHECK ("driver" IN ('api', 'session')),
  "tasks"               jsonb NOT NULL DEFAULT '[]',
  "actions"             jsonb NOT NULL DEFAULT '[]',
  "learnings"           jsonb NOT NULL DEFAULT '[]',
  "report"              text,
  "error"               varchar(4000),
  "usage"               jsonb,
  "userId"              integer,
  "utcStartedDateTime"  timestamptz NOT NULL DEFAULT now(),
  "utcFinishedDateTime" timestamptz,
  CONSTRAINT "UC_JobRun_slot" UNIQUE ("jobId", "slot")
);
CREATE INDEX "IX_JobRun_utcStartedDateTime" ON "JobRun" ("utcStartedDateTime" DESC);

-- A pin someone (or a job) has marked to be looked at again: a date that
-- should firm up, a subject in the news again, a broken picture nobody could
-- replace. The midnight job works the open ones; resolving one keeps the row,
-- with what was done, so the pin's history says why it changed.
--
--   markedBy  the user who marked it; NULL when a job did
--   jobRunId  the run that marked or resolved it, when one did
CREATE TABLE "PinRevisit" (
  "id"                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pinId"                integer NOT NULL REFERENCES "Pin" ("id") ON DELETE CASCADE,
  "reason"               varchar(1000) NOT NULL CONSTRAINT "CK_PinRevisit_reason" CHECK (char_length("reason") >= 1),
  "markedBy"             integer,
  "jobRunId"             integer,
  "resolution"           varchar(2000),
  "utcCreatedDateTime"   timestamptz NOT NULL DEFAULT now(),
  "utcResolvedDateTime"  timestamptz
);
-- At most one open mark per pin: marking it again adds to that one's reason.
CREATE UNIQUE INDEX "UX_PinRevisit_open" ON "PinRevisit" ("pinId") WHERE "utcResolvedDateTime" IS NULL;
