-- Alerts for watched pins: a browser notification when a watched pin starts,
-- and, for those who ask for it, another 15 minutes before.
--
-- 'start' and 'soon' are Notification rows like 'today' (0022), written by a
-- timer in the server (services/watchAlerts.ts) whether or not the watcher has
-- the site open. "pinStart" is the start they were about: the unique index
-- keeps one per user, pin, kind and start however often the timer looks, and
-- a pin moved to another time can alert again.

ALTER TABLE "Notification" ADD COLUMN "pinStart" timestamptz;

CREATE UNIQUE INDEX "UX_Notification_alert" ON "Notification" ("userId", "pinId", "type", "pinStart") WHERE "type" IN ('start', 'soon');

-- The 15-minute reminder, off unless the user turns it on in their preferences.
ALTER TABLE "User" ADD COLUMN "remindBeforeStart" boolean NOT NULL DEFAULT false;

-- Where to send a Web Push: one row per browser that allowed notifications
-- while signed in. The endpoint is the push service's address for that
-- browser; a browser that signs in as someone else moves its row to them.
-- The push service answering 404/410 means the browser dropped it, and the
-- row is deleted.
CREATE TABLE "PushSubscription" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"             integer NOT NULL REFERENCES "User" ("id") ON DELETE CASCADE,
  "endpoint"           text NOT NULL UNIQUE CHECK (length("endpoint") <= 2000),
  "p256dh"             text NOT NULL CHECK (length("p256dh") <= 200),
  "auth"               text NOT NULL CHECK (length("auth") <= 100),
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  "utcUpdatedDateTime" timestamptz
);

CREATE INDEX "IX_PushSubscription_userId" ON "PushSubscription" ("userId");
