-- A click on one of a product pin's buy buttons (src/components/pin/ShopButtons.tsx),
-- for the admin Clicks page: which store, whether the button went to a listing
-- or a search, and who clicked - the signed-in user, else only the address.
--
-- The address is kept for the location and to tell guests apart; the place is
-- looked up from it afterwards (src/server/ipLocation.ts, when the admin page
-- opens), so "country" is null until then. Nothing here is verified: a click
-- is what the browser reported.
CREATE TABLE "ShopClick" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pinId"              integer NOT NULL,
  "store"              varchar(80) NOT NULL,
  "url"                text NOT NULL CHECK (length("url") <= 2000),
  -- A search of the store rather than the product's own listing.
  "search"             boolean NOT NULL,
  -- The price the button showed, if any.
  "price"              numeric(12, 2),
  "currency"           varchar(3),
  "userId"             integer,
  "ip"                 inet,
  -- Where the address places the click (DB-IP): ISO country code, region,
  -- city. "located" is when that was looked up, set even when it found nothing.
  "country"            varchar(2),
  "region"             varchar(120),
  "city"               varchar(120),
  "latitude"           double precision,
  "longitude"          double precision,
  "located"            timestamptz,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "IX_ShopClick_created" ON "ShopClick" ("utcCreatedDateTime");
CREATE INDEX "IX_ShopClick_pin" ON "ShopClick" ("pinId");
CREATE INDEX "IX_ShopClick_unlocated" ON "ShopClick" ("id") WHERE "located" IS NULL AND "ip" IS NOT NULL;
