-- Direct messages between two readers, Messenger-style: the navbar's chats
-- panel, docked chat windows and /messages. One conversation per pair of
-- users ("userLowId" < "userHighId"), so opening a chat with someone finds the
-- one there is. A block (UserBlock) stops new messages either way.
CREATE TABLE "Conversation" (
  "id"                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userLowId"              integer NOT NULL REFERENCES "User" ("id") ON DELETE CASCADE,
  "userHighId"             integer NOT NULL REFERENCES "User" ("id") ON DELETE CASCADE,
  "lastMessageId"          integer,
  "utcCreatedDateTime"     timestamptz NOT NULL DEFAULT now(),
  "utcLastMessageDateTime" timestamptz,
  CONSTRAINT "UC_Conversation_pair" UNIQUE ("userLowId", "userHighId"),
  CONSTRAINT "CK_Conversation_order" CHECK ("userLowId" < "userHighId")
);
CREATE INDEX "IX_Conversation_userHighId" ON "Conversation" ("userHighId");

-- Each side's place in the conversation: the newest message they have seen,
-- which is both their unread state and the other side's "Seen" mark.
CREATE TABLE "ConversationMember" (
  "conversationId"    integer NOT NULL REFERENCES "Conversation" ("id") ON DELETE CASCADE,
  "userId"            integer NOT NULL REFERENCES "User" ("id") ON DELETE CASCADE,
  "lastReadMessageId" integer,
  PRIMARY KEY ("conversationId", "userId")
);
CREATE INDEX "IX_ConversationMember_userId" ON "ConversationMember" ("userId");

CREATE TABLE "Message" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversationId"     integer NOT NULL REFERENCES "Conversation" ("id") ON DELETE CASCADE,
  "senderId"           integer NOT NULL REFERENCES "User" ("id") ON DELETE CASCADE,
  "body"               text NOT NULL,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "CK_Message_body" CHECK (char_length("body") BETWEEN 1 AND 4000)
);
CREATE INDEX "IX_Message_conversationId_id" ON "Message" ("conversationId", "id" DESC);
