-- Marketplace listings on a product pin: "Sell this item here" under the
-- pin's Buy on row. A listing's kind is the pin's own (src/lib/listings.ts
-- listingKindOf: an item, a vehicle, a home or a job), and what the form asks
-- for each kind is kept in "details". Photos and the one video are blob names
-- in the thumb container ("listing/<userId>-<uuid>.jpg"), as uploaded
-- profile pictures are. A listing the seller deletes is only marked, so the
-- ratings given over it stay.
CREATE TABLE "Listing" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pinId"              integer NOT NULL REFERENCES "Pin" ("id") ON DELETE CASCADE,
  "userId"             integer NOT NULL REFERENCES "User" ("id") ON DELETE CASCADE,
  "kind"               varchar(10) NOT NULL,
  "status"             varchar(10) NOT NULL DEFAULT 'available',
  "title"              varchar(150) NOT NULL,
  "price"              numeric(12, 2),
  "currency"           char(3) NOT NULL DEFAULT 'USD',
  "description"        text NOT NULL DEFAULT '',
  "details"            jsonb NOT NULL DEFAULT '{}',
  "photos"             text[] NOT NULL DEFAULT '{}',
  "video"              text,
  "locationLatitude"   double precision,
  "locationLongitude"  double precision,
  "locationName"       varchar(200),
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  "utcUpdatedDateTime" timestamptz NOT NULL DEFAULT now(),
  "utcDeletedDateTime" timestamptz,
  CONSTRAINT "CK_Listing_kind" CHECK ("kind" IN ('item', 'vehicle', 'home', 'job')),
  CONSTRAINT "CK_Listing_status" CHECK ("status" IN ('available', 'pending', 'sold')),
  CONSTRAINT "CK_Listing_title" CHECK (char_length("title") >= 1),
  CONSTRAINT "CK_Listing_price" CHECK ("price" IS NULL OR "price" >= 0),
  CONSTRAINT "CK_Listing_description" CHECK (char_length("description") <= 5000),
  CONSTRAINT "CK_Listing_photos" CHECK (cardinality("photos") <= 50)
);
CREATE INDEX "IX_Listing_pinId" ON "Listing" ("pinId") WHERE "utcDeletedDateTime" IS NULL;
CREATE INDEX "IX_Listing_userId" ON "Listing" ("userId");

-- The buyer's message that opened a chat about a listing ("Is this still
-- available?"). Turns are counted from the first one, and the chat shows the
-- listing it is about.
ALTER TABLE "Message" ADD COLUMN "listingId" integer REFERENCES "Listing" ("id") ON DELETE SET NULL;
CREATE INDEX "IX_Message_listingId" ON "Message" ("listingId") WHERE "listingId" IS NOT NULL;

-- A buyer rates the seller, or the seller a buyer, once their chat about the
-- listing has run seven turns. One rating per listing and rater, which the
-- rater can change. "role" is the side the rated person was on.
CREATE TABLE "ListingRating" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "listingId"          integer NOT NULL REFERENCES "Listing" ("id") ON DELETE CASCADE,
  "raterId"            integer NOT NULL REFERENCES "User" ("id") ON DELETE CASCADE,
  "rateeId"            integer NOT NULL REFERENCES "User" ("id") ON DELETE CASCADE,
  "role"               varchar(6) NOT NULL,
  "stars"              smallint NOT NULL,
  "tags"               text[] NOT NULL DEFAULT '{}',
  "body"               text NOT NULL DEFAULT '',
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  "utcUpdatedDateTime" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "UC_ListingRating" UNIQUE ("listingId", "raterId"),
  CONSTRAINT "CK_ListingRating_role" CHECK ("role" IN ('seller', 'buyer')),
  CONSTRAINT "CK_ListingRating_stars" CHECK ("stars" BETWEEN 1 AND 5),
  CONSTRAINT "CK_ListingRating_body" CHECK (char_length("body") <= 750),
  CONSTRAINT "CK_ListingRating_self" CHECK ("raterId" <> "rateeId")
);
CREATE INDEX "IX_ListingRating_rateeId" ON "ListingRating" ("rateeId");
