-- Ad blocks (src/components/ads/AdBlock.tsx): the slots marked on the timeline
-- and the pin page, filled with Amazon Associates links.
--
-- "Ad" holds the program ads: Amazon's Special Program Commissions (fixed
-- bounties for a sign-up), Bonus Events and the Trade-In program, preferred
-- over product links. Their words are the app's own (ads.programs.<program>
-- in src/lib/i18n/messages), so a row is only where the ad goes and who it is
-- for. Product ads are not stored: they are the Amazon listings already on
-- pins (Merchant), read when the ads are picked.
--
-- "store" is the Amazon store the link goes to, by country code. A store is
-- only served once its own Associates id is set (AppSetting "amazonTags");
-- a viewer whose country has no store with ads gets the US ones.
CREATE TABLE "Ad" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program"            varchar(40) NOT NULL,
  "kind"               varchar(10) NOT NULL CHECK ("kind" IN ('special', 'bonus', 'tradein')),
  "store"              varchar(2) NOT NULL DEFAULT 'US',
  "url"                text NOT NULL CHECK (length("url") <= 2000),
  -- Categories it suits, boosted for viewers and pins leaning to them; empty
  -- for an ad that suits anyone.
  "categories"         text[] NOT NULL DEFAULT '{}',
  -- How often it comes up next to the others of its kind, before the
  -- reward and per-slot performance factors below (src/lib/ads.ts).
  "weight"             real NOT NULL DEFAULT 1 CHECK ("weight" >= 0),
  -- The flat bounty this program's own "Home Page" link pays on a
  -- conversion, from the account's rate card; null for Trade-In (a
  -- percentage of whatever is traded in, not a flat figure) and for a
  -- product ad. Nudges weight up a little for a richer program
  -- (rewardWeight) - never the deciding factor on its own.
  "rewardUsd"          real CHECK ("rewardUsd" > 0),
  -- Never shown to a signed-in viewer younger than this (a sign-up needs an
  -- adult Amazon account), and preferred for ages inside the target range.
  "minAge"             smallint NOT NULL DEFAULT 18,
  "targetAgeFrom"      smallint,
  "targetAgeTo"        smallint,
  "active"             boolean NOT NULL DEFAULT true,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("program", "store")
);

-- How many times each ad was served, per UTC day, slot and store. "adKey" is
-- "ad:<Ad id>" or "m:<Merchant id>" for a product.
CREATE TABLE "AdImpression" (
  "day"    date NOT NULL,
  "adKey"  varchar(40) NOT NULL,
  "kind"   varchar(10) NOT NULL,
  "slot"   varchar(30) NOT NULL,
  "store"  varchar(2) NOT NULL,
  "count"  integer NOT NULL DEFAULT 0,
  PRIMARY KEY ("day", "adKey", "slot", "store")
);

-- A click on an ad, placed afterwards from its address like ShopClick (0086).
CREATE TABLE "AdClick" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "adKey"              varchar(40) NOT NULL,
  "kind"               varchar(10) NOT NULL,
  "program"            varchar(40),
  -- The product's own pin, for a product ad.
  "adPinId"            integer,
  "slot"               varchar(30) NOT NULL,
  -- The pin whose page showed it; null on the timeline.
  "pinId"              integer,
  "store"              varchar(2) NOT NULL,
  "url"                text NOT NULL CHECK (length("url") <= 2000),
  "userId"             integer,
  "ip"                 inet,
  "country"            varchar(2),
  "region"             varchar(120),
  "city"               varchar(120),
  "latitude"           double precision,
  "longitude"          double precision,
  "located"            timestamptz,
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "IX_AdClick_created" ON "AdClick" ("utcCreatedDateTime");
CREATE INDEX "IX_AdClick_unlocated" ON "AdClick" ("id") WHERE "located" IS NULL AND "ip" IS NOT NULL;

-- The US program ads, checked against the account's actual rate card
-- (affiliate-program.amazon.com Rate Plan, 2026-10-02) rather than the public
-- generic fee schedule: Special Program Commissions (Prime free trial/paid
-- membership $40 - by far the richest bounty here, so it carries most of the
-- "special" pool's weight; Audible Standard free trial/monthly $20; Amazon
-- Business signup $15; Prime Video free trial $2 - the $5 "first stream"
-- bounty has no referral link, it is credited automatically; Amazon Haul
-- first purchase $4), Bonus Events (Amazon Fresh $1 and pet supplies $3 per
-- high-value transaction) and Trade-In (4% on Consumer Electronics, Trade
-- Books and Video Games; nothing on other products). URLs are each bounty's
-- own "Home Page" from that rate card, not a guessed/shortened variant, so
-- the click is credited to the right bounty; the tag is added when served.
--
-- The rate card lists ~25 more bounty events (Kindle Unlimited, Amazon Music
-- Unlimited, Prime Video add-on subscriptions, baby/wedding registries, SNAP
-- EBT, Subscribe & Save per category, smaller Audible/Kindle gift-membership
-- tiers) at $0.25-$25 each; left out as either too niche for a general
-- rotating slot or already covered by the flagship program above it.
--
-- "weight" is deliberately the same (1-1.5) across the "special" pool now
-- that rewardUsd carries Prime's and Audible's real edge over the others -
-- see rewardWeight in src/lib/ads.ts. Trade-In has no rewardUsd (its 4% is a
-- cut of whatever is traded in, not a flat bounty).
INSERT INTO "Ad" ("program", "kind", "url", "categories", "weight", "rewardUsd", "targetAgeFrom", "targetAgeTo") VALUES
  ('prime', 'special', 'https://www.amazon.com/prime', '{}', 1.5, 40, NULL, NULL),
  ('audible', 'special', 'https://www.amazon.com/hz/audible/mlp', '{Literature,Manga,Education,Science,Business}', 1.5, 20, 25, NULL),
  ('business', 'special', 'https://business.amazon.com', '{Business,Economy,Finance,Retail,Software,Computing,Labour}', 1, 15, 25, 64),
  ('primevideo', 'special', 'https://www.amazon.com/gp/video/storefront', '{Movie,TV,Anime,Sports}', 1.5, 2, 18, 44),
  ('haul', 'special', 'https://www.amazon.com/haul/store', '{Fashion,Retail}', 1, 4, 18, 34),
  ('fresh', 'bonus', 'https://www.amazon.com/fresh', '{Food,Health,Festival}', 1, 1, 25, NULL),
  ('pets', 'bonus', 'https://www.amazon.com/pet-supplies/b?node=2619533011', '{}', 0.6, 3, 25, NULL),
  ('tradein', 'tradein', 'https://www.amazon.com/tradein', '{Electronics,Gaming,Computing,Audio,Telecom,Semiconductors,Literature}', 1, NULL, 18, 44);
