-- Product ads chosen for one pin (src/server/model/pinAd.ts): an Amazon
-- listing that suits what the pin is about, served first in that pin's ad
-- slots and as a product ad elsewhere. Unlike Merchant (the listings a pin
-- itself is about, shown as buy buttons) these are advertising, so they only
-- carry well-reviewed products from trusted brands (src/lib/adQuality.ts).
--
-- The 6am/6pm news job's pinAds task keeps them alive: it re-reads every
-- listing, marks one "broken" when it is gone, out of stock or no longer
-- meets the bar, and adds similar listings for pins left short.
CREATE TABLE "PinAd" (
  "id"                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pinId"               integer NOT NULL REFERENCES "Pin" ("id") ON DELETE CASCADE,
  "asin"                varchar(10) NOT NULL,
  -- The listing without tracking parameters ("https://www.amazon.com/dp/<asin>");
  -- the Associates tag is added when served.
  "url"                 text NOT NULL CHECK (length("url") <= 300),
  "title"               varchar(300) NOT NULL,
  "brand"               varchar(120),
  "price"               numeric(18,2),
  -- Stars out of 5 and how many reviews they come from, as last read.
  "rating"              numeric(2,1),
  "reviewCount"         integer,
  -- ok: serve it. broken: last read found it gone, out of stock or below the
  -- bar; kept as a record and never served. A listing whose page could not be
  -- read (a robot check) keeps its status.
  "status"              varchar(10) NOT NULL DEFAULT 'ok' CHECK ("status" IN ('ok', 'broken')),
  "problem"             text,
  "checkedDateTime"     timestamptz NOT NULL DEFAULT now(),
  "utcCreatedDateTime"  timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("pinId", "asin")
);
CREATE INDEX "IX_PinAd_status" ON "PinAd" ("status", "pinId");
