-- Product ads for the cultural holidays (src/lib/culturalDays.ts): the goods
-- people traditionally buy for one - mooncakes and lanterns for the
-- Mid-Autumn Festival, menorahs for Hanukkah - served from a month before the
-- holiday to three weeks after (src/server/model/ad.ts). Like PinAd they are
-- Amazon listings that clear a bar for reviews and brand, kept alive by the
-- 6am/6pm news job's holidayAds task, which reads each again, marks one
-- "broken" when it is gone or out of stock, and adds listings for a holiday
-- that has none in one of its price tiers.
CREATE TABLE "HolidayAd" (
  "id"                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- A catalog id ("mid-autumn"), not a foreign key: the catalog is code.
  "holiday"             varchar(40) NOT NULL,
  "asin"                varchar(10) NOT NULL,
  -- The listing without tracking parameters; the Associates tag is added when served.
  "url"                 text NOT NULL CHECK (length("url") <= 300),
  "title"               varchar(300) NOT NULL,
  "brand"               varchar(120),
  "price"               numeric(18,2),
  "rating"              numeric(2,1),
  "reviewCount"         integer,
  -- The product's picture on Amazon's image host.
  "image"               text CHECK (length("image") <= 300),
  -- Which of the holiday's three price bands the price falls in (the catalog
  -- sets the bands): a holiday shows an inexpensive, a middle and an
  -- expensive choice together.
  "tier"                varchar(8) NOT NULL CHECK ("tier" IN ('value', 'mid', 'premium')),
  -- ok: serve it. broken: last read found it gone, out of stock or below the
  -- bar. A page that could not be read (a robot check) keeps its status.
  "status"              varchar(10) NOT NULL DEFAULT 'ok' CHECK ("status" IN ('ok', 'broken')),
  "problem"             text,
  "checkedDateTime"     timestamptz NOT NULL DEFAULT now(),
  "utcCreatedDateTime"  timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("holiday", "asin")
);
CREATE INDEX "IX_HolidayAd_status" ON "HolidayAd" ("status", "holiday");

-- The holidayAds task joins the news job (6am and 6pm) of settings saved
-- before it existed; a default that is not saved needs nothing. Run order is
-- fixed by the task list in src/lib/dailyJobs.ts, so where it sits in the
-- saved list does not matter.
UPDATE "AppSetting"
SET "value" = jsonb_set("value", '{jobs}', (
      SELECT jsonb_agg(
        CASE WHEN "j" ->> 'id' = 'news' AND NOT (("j" -> 'tasks') @> '"holidayAds"'::jsonb)
             THEN jsonb_set("j", '{tasks}', ("j" -> 'tasks') || '"holidayAds"'::jsonb)
             ELSE "j" END)
      FROM jsonb_array_elements("value" -> 'jobs') AS "j")),
    "utcUpdatedDateTime" = now()
WHERE "key" = 'dailyJobs' AND jsonb_typeof("value" -> 'jobs') = 'array';
