-- A company's C-suite and what each was paid, for the company panel (a
-- company: search): the people who hold a chief-officer seat, their base
-- salary and their total compensation (salary, bonus, stock and other pay) for
-- one fiscal year, as the company reported it - in the US, the Summary
-- Compensation Table of its proxy statement (DEF 14A), which is why `sourceUrl`
-- is kept and shown. A private company, or one outside the US, publishes no
-- pay, so a person can be listed with NULL salary and total (shown as "not
-- disclosed"). Filled by `npm run companies:executives`, on the dev machine;
-- prod stores what a local run sends it (PUT /api/companies/:id/executives).
CREATE TABLE "CompanyExecutive" (
  "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "companyId"          integer NOT NULL REFERENCES "Company" ("id") ON DELETE CASCADE,
  "name"               varchar(200) NOT NULL,
  -- "Chief Executive Officer", "President and CFO": as the company writes it.
  "title"              varchar(200) NOT NULL,
  -- 1 chief executive, 2 president, 3 finance, 4 operating, 5 technology,
  -- 6 any other chief officer: the order the panel lists them in.
  "rank"               smallint NOT NULL DEFAULT 6 CONSTRAINT "CK_CompanyExecutive_rank" CHECK ("rank" BETWEEN 1 AND 9),
  -- Whole units of `currency` for the fiscal year `fiscalYear`.
  "salary"             bigint CONSTRAINT "CK_CompanyExecutive_salary" CHECK ("salary" >= 0),
  "totalCompensation"  bigint CONSTRAINT "CK_CompanyExecutive_total" CHECK ("totalCompensation" >= 0),
  "currency"           char(3) NOT NULL DEFAULT 'USD',
  "fiscalYear"         smallint,
  "sourceUrl"          text,
  -- 'sec' (read from a filing by the script), 'hand' (set by the session).
  "origin"             varchar(16) NOT NULL DEFAULT 'hand' CONSTRAINT "CK_CompanyExecutive_origin" CHECK ("origin" IN ('sec', 'claude', 'hand')),
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now(),
  "utcUpdatedDateTime" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "UC_CompanyExecutive_companyId_name" UNIQUE ("companyId", "name")
);
CREATE INDEX "IX_CompanyExecutive_companyId" ON "CompanyExecutive" ("companyId");
