-- Standalone Amazon products, served in the existing product ad pool without
-- attaching unrelated bestsellers to a timeline pin. Facts are read from Amazon
-- and must pass the same quality checks as PinAd.
CREATE TABLE "ProductAd" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asin" varchar(10) NOT NULL UNIQUE,
  "url" text NOT NULL,
  "title" varchar(300) NOT NULL,
  "brand" varchar(120),
  "price" numeric(18,2),
  "rating" numeric(2,1),
  "reviewCount" integer,
  "image" text,
  "urgency" varchar(30),
  "categories" text[] NOT NULL DEFAULT '{}',
  "status" varchar(10) NOT NULL DEFAULT 'ok' CHECK ("status" IN ('ok', 'broken')),
  "problem" text,
  "checkedDateTime" timestamptz NOT NULL DEFAULT now(),
  "utcCreatedDateTime" timestamptz NOT NULL DEFAULT now()
);
